Оптимизируй это (Часть 1)
htmlacademy-react/789949-six-cities-8 pull request #13
Opened 2021-11-12 17:00 UTC by vassilyf

2021-11-12 20:45 UTC, Razzwan requested changes

2021-11-12 20:45 UTC, Razzwan commented on package.json
> +    "react-devtools": "^4.21.0",
Эта зависимость должно быть в devDependencies . Не нашел использования в коде

2021-11-12 20:45 UTC, Razzwan commented on package.json
> +    "redux-devtools": "^3.7.0",
Не нашел использования

2021-11-12 20:45 UTC, Razzwan commented on src/components/app/app.tsx
> +const mapStateToProps = ({OFFERS, AUTH}: State) => ({
OFFERS и AUTH - это переменные. Обычно используют нижний регистр для них

2021-11-12 20:45 UTC, Razzwan commented on src/components/cities-list/cities-list.tsx
> +const mapStateToProps = ({OFFERS: {city}}: State) => ({
Лучше избегать вложенной деструктуризации. Она может вызывать неотлавливаемые исключения в случае, если `OFFERS` будет undefined

2021-11-12 20:45 UTC, Razzwan commented on src/components/favorites/favorites.tsx
> +  favorites.reduce( (map: FavoritesMap, offer) => {
`map` - ключевое слово. лучше его избегать для обозначения переменной в таком контексте

2021-11-12 20:45 UTC, Razzwan commented on src/store/reducer.ts
> +  auth = 'AUTH',
Если мы задали пространство имен, то при получении данных нам нужно его использовать, иначе, какой в этом смысл, если мы все равно используем строковые литералы вместо этого?

2021-11-12 20:45 UTC, Razzwan commented on src/store/reducers/offers-process.ts
> +  allCitiesNames: ['Paris', 'Cologne', 'Brussels', 'Amsterdam', 'Hamburg', 'Dusseldorf'],
Снова, задали переменную для Парижа, но забыли ее здесь использовать...

2021-11-12 20:45 UTC, Razzwan commented on src/store/reducers/offers-process.ts
> +const getCityWithLocation = createSelector( (state: OffersState, cityName: string) => state.allCitiesData, (state: OffersState, cityName: string) => cityName,
Я бы размещал селекторы в отдельном файле, ведь это не редюсер. Можем созвониться - пообщаться на эту тему

2021-11-12 20:45 UTC, Razzwan commented on src/types/types.ts
> +//export type State = AuthState & OffersState & DetailsState & FavoritesState;
Удалить закомментированное

2021-11-13 10:02 UTC, vassilyf commented
исправил

2021-11-13 16:28 UTC, merged